# Change these first
owner: topminevn # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: TopMine Minecraft Network
    url: mc.topmine.vip
    port: 25565
    check: "tcp-ping"
    ipv6: false

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.topmine.vip
  #baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: TopMineVN
  introTitle: "Status của TopMineVN server"
  introMessage: Trang này giúp bạn theo dõi trạng thái server Minecraft của TopMineVN cũng như lịch sử trạng thái. Chỉ bao gồm thông tin về main network server, không bao gồm chi tiết từng gamemode Skyblock, Survival,...
  navbar:
    - title: Status
      href: /
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO

assignees:
  - SaitDev
skipDeleteIssues: false

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
